/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ck35_raspberry_sensors_temperature_DHTSensor */

#ifndef _Included_de_ck35_raspberry_sensors_temperature_DHTSensor
#define _Included_de_ck35_raspberry_sensors_temperature_DHTSensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ck35_raspberry_sensors_temperature_DHTSensor
 * Method:    readNative
 * Signature: (II)[F
 */
JNIEXPORT jfloatArray JNICALL Java_de_ck35_raspberry_sensors_temperature_DHTSensor_readNative
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
